<a href="https://colab.research.google.com/github/renatamontanhana/Pandas_diferentes_formatos_de_arquivos/blob/main/pandas_trabalhando_diferentes_formatos_de_arquivos_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
dados_pacientes = pd.read_json('/content/pacientes.json')

In [5]:
dados_pacientes

,ID_paciente,Doenca_cardiaca,IMC,Fumante,Consumo_alcool,AVC,Saude_fisica,Saude_mental,Dificuldade_caminhar,Sexo_biologico,Faixa_etaria,Raca,Diabetes,Atividade_fisica,Saude_geral,Horas_sono,Asma,Doenca_renal,Cancer_pele
0,0,Nao,16.60,Sim,Nao,Nao,3,30,Nao,Feminino,55-59,Branca,Sim,Sim,Muito boa,5,Sim,Nao,Sim
1,1,Nao,20.34,Nao,Nao,Sim,0,0,Nao,Feminino,80 ou +,Branca,Nao,Sim,Muito boa,7,Nao,Nao,Nao
2,2,Nao,26.58,Sim,Nao,Nao,20,30,Nao,Masculino,65-69,Branca,Sim,Sim,Razoavel,8,Sim,Nao,Nao
3,3,Nao,24.21,Nao,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,No,Boa,6,Nao,Nao,Sim
4,4,Nao,23.71,Nao,Nao,Nao,28,0,Sim,Feminino,40-44,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Nao,28.29,Sim,Nao,Nao,10,20,Nao,Feminino,65-69,Preta,Sim,Sim,Razoavel,8,Nao,Nao,Nao
996,996,Nao,25.69,Sim,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,Sim,Excelente,8,Nao,Nao,Nao
997,997,Sim,26.99,Nao,Nao,Nao,1,0,Nao,Masculino,70-74,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
998,998,Nao,44.29,Nao,Nao,Nao,30,0,Sim,Feminino,70-74,Branca,Sim,No,Boa,6,Sim,Nao,Nao
999,999,Nao,25.83,Nao,Nao,Nao,0,0,Nao,Masculino,70-74,Preta,Sim,No,Excelente,7,Nao,Nao,Nao

In [6]:
dados_pacientes_2 = pd.read_json('/content/pacientes_2.json')

In [7]:
dados_pacientes_2

,Pesquisa,Ano,Pacientes
0,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi..."
1,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_..."
2,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi..."

In [8]:
df_normalizado = pd.json_normalize(dados_pacientes_2['Pacientes'])

In [9]:
df_normalizado

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [10]:
dados_dict = {
  "Pesquisa": "Principais Indicadores de Doenca Cardiaca",
  "Ano": 2020,
  "Pacientes": [
    {
      "ID": "01",
      "Faixa_etaria": "55-59",
      "Sexo_biologico": "Feminino",
      "Raça": "Branca",
      "IMC": 16.6,
      "Fumante": "Sim",
      "Consumo_alcool": "Nao",
      "Saude_fisica": 3,
      "Saude_mental": 30,
      "Dificuldade_caminhar": "Nao",
      "Atividade_fisica": "Sim",
      "Saude_geral": "Muito boa",
      "Horas_sono": 5,
      "Problemas_saude": [
        "Diabetes",
        "Asma",
        "Cancer_pele"
      ]
    },
    {
      "ID": "02",
      "Faixa_etaria": "80 ou +",
      "Sexo_biologico": "Feminino",
      "Raça": "Branca",
      "IMC": 20.34,
      "Fumante": "Nao",
      "Consumo_alcool": "Nao",
      "Saude_fisica": 0,
      "Saude_mental": 0,
      "Dificuldade_caminhar": "Nao",
      "Atividade_fisica": "Sim",
      "Saude_geral": "Muito boa",
      "Horas_sono": 7,
      "Problemas_saude": [
        "AVC"
      ]
    },
    {
      "ID": "03",
      "Faixa_etaria": "65-69",
      "Sexo_biologico": "Masculino",
      "Raça": "Branca",
      "IMC": 26.58,
      "Fumante": "Sim",
      "Consumo_alcool": "Nao",
      "Saude_fisica": 20,
      "Saude_mental": 30,
      "Dificuldade_caminhar": "Nao",
      "Atividade_fisica": "Sim",
      "Saude_geral": "Muito boa",
      "Horas_sono": 8,
      "Problemas_saude": [
        "diabetes",
        "Asma"
      ]
    }
  ]
}

In [11]:
pd.json_normalize(dados_dict)

,Pesquisa,Ano,Pacientes
0,Principais Indicadores de Doenca Cardiaca,2020,"[{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_b..."

In [12]:
pd.json_normalize(dados_dict['Pacientes'])

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [13]:
pd.json_normalize(dados_dict, record_path=['Pacientes'])

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [14]:
pd.json_normalize(
    dados_dict,
    record_path =['Pacientes'],
    meta=['Pesquisa', 'Ano']
)

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude,Pesquisa,Ano
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]",Principais Indicadores de Doenca Cardiaca,2020
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC],Principais Indicadores de Doenca Cardiaca,2020
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]",Principais Indicadores de Doenca Cardiaca,2020

In [15]:
#Importando a biblioteca Pandas
import pandas as pd

#Importando o módulo JSON
import json

#Lendo o arquivo json usando o módulo Python JSON
with open('pacientes_2.json','r') as f:
    dados = json.loads(f.read())

#Normalizando os dados com os parâmetros record_path e meta
pd.json_normalize(dados, record_path='Pacientes', meta=['Pesquisa', 'Ano'])

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude,Pesquisa,Ano
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]",Principais Indicadores de Doenca Cardiaca,2020
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC],Principais Indicadores de Doenca Cardiaca,2020
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]",Principais Indicadores de Doenca Cardiaca,2020

In [16]:
df_normalizado.to_json('historico_pacientes_normalizado.json')

In [17]:
pd.read_json('/content/historico_pacientes_normalizado.json')

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,1,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,2,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,3,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [18]:
import requests
import json

In [19]:
dados_frutas = requests.get('https://fruityvice.com/api/fruit/all')

In [20]:
resultado = json.loads(dados_frutas.text)

In [21]:
pd.DataFrame(resultado)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Papaya,42,Caricaceae,Caricacea,Carica,"{'calories': 43, 'fat': 0.4, 'sugar': 1.0, 'ca..."
26,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
27,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
28,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
29,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
30,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
31,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
32,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
33,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
34,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
35,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
36,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
37,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
38,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
39,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
40,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
41,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."

In [22]:
import requests
import json

dados_frutas = requests.get('https://fruityvice.com/api/fruit/all')
resultado = json.loads(dados_frutas.text)

In [23]:
import pandas as pd
dados_frutas_normalizado = pd.json_normalize(resultado)

In [24]:
dados_frutas_normalizado

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Papaya,42,Caricaceae,Caricacea,Carica,43,0.40,1.00,11.00,0.00
26,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
27,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
28,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
29,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
30,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
31,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
32,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
33,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
34,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
35,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
36,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
37,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
38,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
39,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
40,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
41,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78